---
- name      : Restart nginx
  service   :
    name    : nginx
    state   : restarted
    enabled : yes
  become    : yes

- name      : Restart supervisor
  service   :
    name    : supervisord
    state   : restarted
    enabled : yes
  become    : yes
