---
- name        : Add PostgreSQL repository
  yum         :
    name      : http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-2.noarch.rpm

- name        : Install PostgreSQL
  yum         : name={{item}}
  with_items  :
    - postgresql94-server
    - postgresql94-devel
    - postgresql94-contrib
