---
- name        : Check database created
  command     : psql postgres -tAc "SELECT COUNT(*) FROM pg_roles WHERE rolname='redash'"
  become      : yes
  become_user : postgres
  register    : created_database

- name        : Create Re:dash database user
  command     : createuser redash --no-superuser --no-createdb --no-createrole
  become      : yes
  become_user : postgres
  when        : created_database.stdout == '0'

- name        : Create Re:dash database
  command     : createdb redash --owner=redash
  become      : yes
  become_user : postgres
  when        : created_database.stdout == '0'

- name        : Create tables
  command     : bin/run ./manage.py database create_tables
  args        :
    chdir     : /opt/redash/current
  become      : yes
  become_user : redash
  when        : created_database.stdout == '0'
