---
- include_vars  : timezone-vars.yml

- name          : Check Timezone
  shell         : timedatectl status | grep "Time zone"
  register      : current_timezone
  ignore_errors : yes

- name          : set timezone
  become        : yes
  command       : timedatectl set-timezone {{ timezone }}
  when          : not '{{ timezone }}' in current_timezone.stdout
